# Application name
spring.application.name=honeyRest_host

# Server port
server.port=8080

# Database configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/honey_rest_db
# cloud = tjfgusdh
# normal = honeyRest_host
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# defined in application-secret.properties
spring.datasource.username=${spring.datasource.username}
# defined in application-secret.properties
spring.datasource.password=${spring.datasource.password}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cache configuration
spring.cache.type=simple

# Swagger (API documentation)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# defined in application-secret.properties
spring.mail.username=${spring.mail.username}
# defined in application-secret.properties
spring.mail.password=${spring.mail.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth2 (Google login)
spring.security.oauth2.client.registration.google.client-id=${google.client-id} # defined in application-secret.properties
spring.security.oauth2.client.registration.google.client-secret=${google.client-secret} # defined in application-secret.properties
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

# Logging configuration
# Global logging level
logging.level.root=info

# Spring framework logs
logging.level.org.springframework=info

# Web request handling
logging.level.org.springframework.web=debug

# Spring Security logs
logging.level.org.springframework.security=debug

# Hibernate SQL logs
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

# Thymeleaf template engine (if used)
logging.level.org.thymeleaf=info


# Import secret configuration file
spring.config.import=optional:application_secret.properties

# JWT configuration
# defined in application-secret.properties
jwt.secret=hello1234567890hello1234567890hello1234567890hello1234567890
jwt.expiration-ms=3600000

# S3 ???? ?
spring.cloud.aws.s3.enabled=false

# (??? ??? ???? ???)
spring.autoconfigure.exclude=io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

