# Database credentials
spring.datasource.username= root
spring.datasource.password= 4464

# Mail credentials
spring.mail.username=swp20138993@gmail.com
spring.mail.password=tj937199thth~~

## OAuth2 credentials (Google)
#google.client-id=your_google_client_id
#google.client-secret=your_google_client_secret
#
## JWT secret key
#jwt.secret=your_jwt_secret_key